// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>


const char THING_ID[]           = MY_THING_ID;
const char DEVICE_LOGIN_NAME[]  = MY_DEVICE_LOGIN_NAME;

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

CloudTemperatureSensor t0;
CloudTemperatureSensor t1;
CloudTemperatureSensor t2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.setThingId(THING_ID);
  ArduinoCloud.addProperty(t0, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(t1, READ, 60 * SECONDS, NULL);
  ArduinoCloud.addProperty(t2, READ, 60 * SECONDS, NULL);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
